apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: jpgough/hello
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: world
spec:
  selector:
    matchLabels:
      app: world
  replicas: 1
  template:
    metadata:
      labels:
        app: world
    spec:
      containers:
        - name: world
          image: jpgough/world
          ports:
            - containerPort: 8080