apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    app: hello-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: hello
  #Needed for Docker Desktop
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: world
  labels:
    app: world
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: world